version: '2'

services:
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
  web:
    image: dfk/cld:3.0
    ##
    # We can if we like let docker-compose buiöd this image if it sees changes to the Dockerfile
    #
    #build: .

    ##
    # For local development its easy to replace the contants inside the container to something on
    # this local machine instead.
    #
    #volumes:
    #  - ./www:/www